name: pre-commit

on:
    workflow_call:
      inputs:
        vllm:
          required: true
          type: string

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: linux-amd64-cpu-8
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/vllm-ascend:nightly-cpu
    env:
      GOPROXY: https://goproxy.io,direct
    steps:
    - name: Checkout vllm-project/vllm-ascend repo
      uses: actions/checkout@v6
    - run: echo "::add-matcher::.github/workflows/matchers/actionlint.json"
    - run: echo "::add-matcher::.github/workflows/matchers/mypy.json"
    - name: Checkout vllm-project/vllm repo
      uses: actions/checkout@v6
      with:
        repository: vllm-project/vllm
        path: ./vllm-empty
        ref: ${{ inputs.vllm }}
    - name: Install vllm
      working-directory: vllm-empty
      run: |
        VLLM_TARGET_DEVICE=empty python3 -m pip install .
    - name: Install vllm-ascend dev
      run: |
        git config --global --add safe.directory /__w/vllm-ascend/vllm-ascend
        pip install -r requirements-dev.txt --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Run pre-commit
      env:
        PRE_COMMIT_COLOR: always
        FORCE_COLOR: "1"
        TERM: xterm-256color
        SHELLCHECK_OPTS: "--exclude=SC2046,SC2006,SC2086" # Exclude SC2046, SC2006, SC2086 for actionlint
      run: |
        pre-commit run --all-files --hook-stage manual
